version: '3.5'

services:
  lanars-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: lanars
    volumes:
      - lanars-api-db:/var/lib/postgresql/lanars

  lanars-api-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "7000:9000"
      - "7001:9001"
    volumes:
      - /lanars-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

volumes:
  lanars-api-db:
  lanars-api-s3:
